# Generated by Django 2.1.5 on 2019-04-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_auto_20190413_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denomarmalizedvotes',
            name='voter_id_h',
            field=models.CharField(default='6af585a470904c46a5e4a188ffbc58ce', max_length=255, unique=True, verbose_name='Hashed Voter ID'),
        ),
    ]
