# Generated by Django 2.1.5 on 2019-04-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_auto_20190413_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='denomarmalizedvotes',
            name='candidate_class_grade_level',
            field=models.CharField(db_index=True, max_length=20, null=True, verbose_name='Grade Level'),
        ),
        migrations.AddField(
            model_name='denomarmalizedvotes',
            name='candidate_class_school_year',
            field=models.CharField(db_index=True, max_length=15, null=True, verbose_name='School Year'),
        ),
        migrations.AddField(
            model_name='denomarmalizedvotes',
            name='candidate_class_section',
            field=models.CharField(db_index=True, max_length=20, null=True, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='denomarmalizedvotes',
            name='candidate_name',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Candidate Name'),
        ),
        migrations.AddField(
            model_name='denomarmalizedvotes',
            name='voter_class_grade_level',
            field=models.CharField(db_index=True, max_length=20, null=True, verbose_name='Grade Level'),
        ),
        migrations.AddField(
            model_name='denomarmalizedvotes',
            name='voter_class_school_year',
            field=models.CharField(db_index=True, max_length=15, null=True, verbose_name='School Year'),
        ),
        migrations.AddField(
            model_name='denomarmalizedvotes',
            name='voter_class_section',
            field=models.CharField(db_index=True, max_length=20, null=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='denomarmalizedvotes',
            name='candidate_age',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='denomarmalizedvotes',
            name='voter_age',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='denomarmalizedvotes',
            name='voter_id_h',
            field=models.CharField(default='a769a6a2b2df44f2a2bdaf4083c32992', max_length=255, unique=True, verbose_name='Hashed Voter ID'),
        ),
    ]
