# Generated by Django 2.1.5 on 2019-04-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0009_auto_20190413_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denomarmalizedvotes',
            name='candidate_class_school_year',
        ),
        migrations.RemoveField(
            model_name='denomarmalizedvotes',
            name='voter_class_school_year',
        ),
        migrations.AlterField(
            model_name='denomarmalizedvotes',
            name='voter_id_h',
            field=models.CharField(default='efefd2776461454da63cfce66d45002b', max_length=255, unique=True, verbose_name='Hashed Voter ID'),
        ),
    ]
