# Generated by Django 2.1.5 on 2019-04-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0010_auto_20190413_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denomarmalizedvotes',
            name='voter_id_h',
            field=models.CharField(default='af0e197236904d38b1c651312a563e15', max_length=255, verbose_name='Hashed Voter ID'),
        ),
    ]
