# Generated by Django 2.1.5 on 2019-04-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0011_auto_20190413_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denomarmalizedvotes',
            name='candidate_party',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Pary Name'),
        ),
        migrations.AlterField(
            model_name='denomarmalizedvotes',
            name='candidate_position',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='denomarmalizedvotes',
            name='voter_id_h',
            field=models.CharField(default='9b933e5badcb43349664d1611b18da38', max_length=255, verbose_name='Hashed Voter ID'),
        ),
    ]
