# Generated by Django 2.1.5 on 2019-04-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0017_auto_20190414_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denomarmalizedvotes',
            name='voter_id_h',
            field=models.CharField(default='09ad8193b9a6440290e1f701969983d1', max_length=255, verbose_name='Hashed Voter ID'),
        ),
    ]
