# Generated by Django 2.1.5 on 2019-04-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0021_auto_20190416_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenormalizedVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('voter_id_h', models.CharField(default='9ad54a8cbde6477ca64db6bdec199230', max_length=255, verbose_name='Hashed Voter ID')),
                ('voter_sex', models.CharField(db_index=True, max_length=1, verbose_name='Sex')),
                ('voter_age', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='Age')),
                ('voter_mother_tongue', models.CharField(db_index=True, max_length=50, verbose_name='Mother Tongue')),
                ('voter_ethnic_group', models.CharField(db_index=True, max_length=50, verbose_name='Ethnic Group')),
                ('voter_religion', models.CharField(db_index=True, max_length=100, verbose_name='Religion')),
                ('voter_address_barangay', models.CharField(db_index=True, max_length=50, verbose_name='Address Barangay')),
                ('voter_address_municipality', models.CharField(db_index=True, max_length=100, verbose_name='Address Municipality')),
                ('voter_address_province', models.CharField(db_index=True, max_length=100, verbose_name='Address Province')),
                ('voter_class_grade_level', models.CharField(db_index=True, max_length=20, null=True, verbose_name='Grade Level')),
                ('voter_class_section', models.CharField(db_index=True, max_length=20, null=True, verbose_name='Section')),
                ('candidate_name', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Candidate Name')),
                ('candidate_sex', models.CharField(db_index=True, max_length=1, verbose_name='Sex')),
                ('candidate_age', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='Age')),
                ('candidate_mother_tongue', models.CharField(db_index=True, max_length=50, verbose_name='Mother Tongue')),
                ('candidate_ethnic_group', models.CharField(db_index=True, max_length=50, verbose_name='Ethnic Group')),
                ('candidate_religion', models.CharField(db_index=True, max_length=100, verbose_name='Religion')),
                ('candidate_address_barangay', models.CharField(db_index=True, max_length=50, verbose_name='Address Barangay')),
                ('candidate_address_municipality', models.CharField(db_index=True, max_length=100, verbose_name='Address Municipality')),
                ('candidate_address_province', models.CharField(db_index=True, max_length=100, verbose_name='Address Province')),
                ('candidate_class_grade_level', models.CharField(db_index=True, max_length=20, null=True, verbose_name='Grade Level')),
                ('candidate_class_section', models.CharField(db_index=True, max_length=20, null=True, verbose_name='Section')),
                ('candidate_party', models.CharField(db_index=True, max_length=255, verbose_name='Pary Name')),
                ('candidate_position', models.CharField(db_index=True, max_length=100, verbose_name='Title')),
                ('candidate_position_number_of_slots', models.PositiveSmallIntegerField(verbose_name='Number of Slot')),
                ('candidate_position_priority', models.PositiveSmallIntegerField(default=0, verbose_name='Priority')),
                ('election_id', models.PositiveIntegerField(db_index=True)),
                ('election_name', models.CharField(db_index=True, max_length=255)),
                ('election_school_year', models.CharField(db_index=True, max_length=20, verbose_name='School Year')),
                ('election_day_from', models.DateField(db_index=True, verbose_name='Election Start Date')),
                ('election_day_to', models.DateField(db_index=True, verbose_name='Election End Date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='DenomarmalizedVotes',
        ),
    ]
