# Generated by Django 2.1.5 on 2019-04-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0024_auto_20190417_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipationRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('election_id', models.PositiveIntegerField(db_index=True)),
                ('election_name', models.CharField(db_index=True, max_length=255)),
                ('election_school_year', models.CharField(db_index=True, max_length=20, verbose_name='School Year')),
                ('election_day_from', models.DateField(db_index=True, verbose_name='Election Start Date')),
                ('election_day_to', models.DateField(db_index=True, verbose_name='Election End Date')),
                ('group', models.CharField(choices=[('OVERALL', 'OVERALL'), ('GRADE_LEVEL', 'GRADE_LEVEL'), ('SECTION', 'SECTION')], max_length=20)),
                ('group_value', models.CharField(db_index=True, max_length=255)),
                ('total_voters', models.PositiveIntegerField(db_index=True)),
                ('total_casted_votes', models.PositiveIntegerField(db_index=True)),
                ('percentage', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='winnercandidatedenormalized',
            options={'ordering': ('candidate_position_priority',)},
        ),
        migrations.AlterField(
            model_name='denormalizedvotes',
            name='voter_id_h',
            field=models.CharField(default='0cb925f987034ddab25e35f9f54d40bd', max_length=255, verbose_name='Hashed Voter ID'),
        ),
    ]
