# Generated by Django 2.1.5 on 2019-04-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0025_auto_20190418_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participationrate',
            options={'ordering': ('-election_day_to', 'group_value')},
        ),
        migrations.AlterField(
            model_name='denormalizedvotes',
            name='voter_id_h',
            field=models.CharField(default='4b846752405647608e565d63dd925d2e', max_length=255, verbose_name='Hashed Voter ID'),
        ),
    ]
