# Generated by Django 2.1.7 on 2019-06-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0027_auto_20190418_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denormalizedvotes',
            name='voter_id_h',
            field=models.CharField(default='816c5be736e44303bc6c9c43c89d2c8c', max_length=255, verbose_name='Hashed Voter ID'),
        ),
    ]
