# Generated by Django 2.1.5 on 2019-04-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_auto_20190409_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='voter_id_h',
            field=models.CharField(default='79b2f0b6e2254458b4ee34682c736c1d', max_length=255, unique=True, verbose_name='Hashed Voter ID'),
        ),
    ]
