# Generated by Django 2.1.5 on 2019-04-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_auto_20190409_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='voter_id_h',
            field=models.CharField(default='22701c4827b14222b1c0912844804474', max_length=255, unique=True, verbose_name='Hashed Voter ID'),
        ),
    ]
