# Generated by Django 2.1.5 on 2019-04-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_auto_20190409_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='voter_id_h',
            field=models.CharField(default='84d50ea1ce364f168b00f01928a580e8', max_length=255, unique=True, verbose_name='Hashed Voter ID'),
        ),
    ]
