# Generated by Django 2.1.5 on 2019-04-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0008_auto_20190409_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='voter_id_h',
            field=models.CharField(default='9da0bbcdcf3f494ea6639356d5464325', max_length=255, unique=True, verbose_name='Hashed Voter ID'),
        ),
    ]
