# Generated by Django 2.1.5 on 2019-04-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0010_auto_20190413_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='voter_id_h',
            field=models.CharField(default='0251fcbfc7f443979013cdd79628925f', max_length=255, unique=True, verbose_name='Hashed Voter ID'),
        ),
    ]
