# Generated by Django 2.1.5 on 2019-04-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0012_auto_20190413_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='voter_id_h',
            field=models.CharField(default='fe7ea09d05564ac984793a82ec22eba9', max_length=255, unique=True, verbose_name='Hashed Voter ID'),
        ),
    ]
