# Generated by Django 2.1.5 on 2019-04-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0016_auto_20190413_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='voter_id_h',
            field=models.CharField(default='9a203490c3a44c0181e0aadf52624508', max_length=255, unique=True, verbose_name='Hashed Voter ID'),
        ),
    ]
