# Generated by Django 2.1.5 on 2019-04-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0017_auto_20190413_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='voter_id_h',
            field=models.CharField(default='cf2c370db4ad487996ba30a52c6ef568', max_length=255, unique=True, verbose_name='Hashed Voter ID'),
        ),
    ]
