# Generated by Django 2.1.5 on 2019-04-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0018_auto_20190413_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='voter_id_h',
            field=models.CharField(default='3f5db6b1c20c4217be0b0d105c00a686', max_length=255, unique=True, verbose_name='Hashed Voter ID'),
        ),
    ]
