# Generated by Django 2.1.5 on 2019-04-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0021_auto_20190413_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='voter_id_h',
            field=models.CharField(default='355a9a2377b74d0598f788f607083f87', max_length=255, unique=True, verbose_name='Hashed Voter ID'),
        ),
    ]
