# Generated by Django 2.1.5 on 2019-04-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0022_auto_20190413_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='voter_id_h',
            field=models.CharField(default='5251737d7baa45988765684816ecc8e6', max_length=255, unique=True, verbose_name='Hashed Voter ID'),
        ),
    ]
