# Generated by Django 2.1.5 on 2019-04-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0024_auto_20190413_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='voter_id_h',
            field=models.CharField(default='780f2a003e4b461fabba0c8c2fa7bbc4', max_length=255, unique=True, verbose_name='Hashed Voter ID'),
        ),
    ]
