# Generated by Django 2.1.5 on 2019-04-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0033_auto_20190416_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='voter_id_h',
            field=models.CharField(default='17a9ee92579e4c94ab1ae27795428ba7', max_length=255, unique=True, verbose_name='Hashed Voter ID'),
        ),
    ]
