# Generated by Django 2.1.7 on 2019-06-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0034_auto_20190417_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='voter_id_h',
            field=models.CharField(default='5999b889757f47238ad58f6c04ea4012', max_length=255, unique=True, verbose_name='Hashed Voter ID'),
        ),
    ]
