# Generated by Django 2.1.5 on 2019-04-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_ballot_voter_id_h'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='vote_casting_IP',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
