# Generated by Django 2.1.5 on 2019-04-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_auto_20190409_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='voter_id_h',
            field=models.CharField(default='bff33bf21d2b46e2bdf8f5faa3d732e0', max_length=255, unique=True, verbose_name='Hashed Voter ID'),
        ),
    ]
