# Generated by Django 2.1.5 on 2019-04-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0009_auto_20190413_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='voter_id_h',
            field=models.CharField(default='8f3747f64de7456da339317cc0ca1ad2', max_length=255, unique=True, verbose_name='Hashed Voter ID'),
        ),
    ]
