# Generated by Django 2.1.5 on 2019-04-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0011_auto_20190413_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='voter_id_h',
            field=models.CharField(default='4cbe0adade8a449f8c36e546a0111598', max_length=255, unique=True, verbose_name='Hashed Voter ID'),
        ),
    ]
