# Generated by Django 2.1.5 on 2019-04-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0014_auto_20190413_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='voter_id_h',
            field=models.CharField(default='575ee9484cd647feb2f3038626fe6bbb', max_length=255, unique=True, verbose_name='Hashed Voter ID'),
        ),
    ]
