# Generated by Django 2.1.5 on 2019-04-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0019_auto_20190413_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='voter_id_h',
            field=models.CharField(default='3ffce989c90247df96295c505bcfd2e4', max_length=255, unique=True, verbose_name='Hashed Voter ID'),
        ),
    ]
