# Generated by Django 2.1.5 on 2019-04-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0023_auto_20190413_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='voter_id_h',
            field=models.CharField(default='78817884c05a430e8e28ab062c29b616', max_length=255, unique=True, verbose_name='Hashed Voter ID'),
        ),
    ]
