# Generated by Django 2.1.5 on 2019-04-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0027_auto_20190414_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='voter_id_h',
            field=models.CharField(default='26d89bce7a33475d9531ec3b7d407897', max_length=255, unique=True, verbose_name='Hashed Voter ID'),
        ),
    ]
