# Generated by Django 2.1.5 on 2019-04-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0031_auto_20190414_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='voter_id_h',
            field=models.CharField(default='728cdd31ecb6436f8cdbef91562481c4', max_length=255, unique=True, verbose_name='Hashed Voter ID'),
        ),
    ]
