# Generated by Django 2.1.5 on 2019-04-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0032_auto_20190416_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='voter_id_h',
            field=models.CharField(default='25e26cc274d246c5b538a6b675d3f60d', max_length=255, unique=True, verbose_name='Hashed Voter ID'),
        ),
    ]
