# Generated by Django 2.1.5 on 2019-03-06 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0002_auto_20190306_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electionofficer',
            name='id',
        ),
        migrations.AddField(
            model_name='electionofficer',
            name='user_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_query_name='user', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
