# Generated by Django 2.1.5 on 2019-03-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20190306_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electionofficer',
            old_name='user_id',
            new_name='user',
        ),
    ]
