# Generated by Django 2.1.5 on 2019-03-08 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20190306_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionofficer',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='student', to='registration.Student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='electionofficer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_query_name='user', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
