# Generated by Django 2.1.5 on 2019-03-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20190311_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='last_udated_by',
            new_name='last_updated_by',
        ),
    ]
