# Generated by Django 2.1.5 on 2019-03-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20190311_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='students', to='registration.Class', verbose_name='classes'),
        ),
    ]
