# Generated by Django 2.1.5 on 2019-03-15 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_positiongradelevel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positiongradelevel',
            options={'ordering': ('grade_level',)},
        ),
        migrations.AddField(
            model_name='election',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='positiongradelevel',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_levels', related_query_name='grade_levels', to='registration.Position', verbose_name='Position'),
        ),
    ]
