# Generated by Django 2.1.5 on 2019-03-17 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_auto_20190317_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Party', verbose_name='Party'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', related_query_name='students', to='registration.Sex', verbose_name='Sex'),
        ),
    ]
