# Generated by Django 2.1.5 on 2019-03-18 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_auto_20190317_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='registration.Election', verbose_name='Election'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='registration.Party', verbose_name='Party'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='registration.Position', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='registration.Student', verbose_name='Student'),
        ),
    ]
