# Generated by Django 2.1.5 on 2019-03-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_auto_20190321_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='profile_pic',
            field=models.ImageField(blank=True, default='candidate_pics/avatar.png', upload_to='candidate_pics/'),
        ),
    ]
