# Generated by Django 2.1.5 on 2019-03-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0029_election_is_token_generated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['priority', 'title']},
        ),
        migrations.AddField(
            model_name='position',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Priority'),
        ),
    ]
