# Generated by Django 2.1.5 on 2019-03-30 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0030_auto_20190331_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('voter_token', models.CharField(db_index=True, max_length=50, verbose_name='Voter Token')),
                ('candidates', models.ManyToManyField(blank=True, related_name='voters', to='registration.Candidate', verbose_name='Candidates')),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voters', to='registration.Election', verbose_name='Election')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voters', to='registration.Student', verbose_name='Student')),
                ('student_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voters', to='registration.Class', verbose_name='Student Class')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='voter',
            unique_together={('student', 'election')},
        ),
    ]
