# Generated by Django 2.1.5 on 2019-04-09 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_auto_20190409_1707'),
        ('registration', '0033_auto_20190409_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('hashed_id', models.CharField(default='455c2f5cded04f89b7f9527c0e26ecb4', max_length=255)),
                ('ballot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to='election.Ballot', verbose_name='Ballot')),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to='registration.Candidate', verbose_name='Candidate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
