# Generated by Django 2.1.5 on 2019-04-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0037_auto_20190409_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='hashed_id',
            field=models.CharField(default='06eced0649e4405fb34614dc95f2d7ec', max_length=255, unique=True),
        ),
    ]
