# Generated by Django 2.1.5 on 2019-04-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0040_auto_20190413_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='hashed_id',
            field=models.CharField(default='bfc97de821ec44898defefbcdc95b27f', max_length=255, unique=True),
        ),
    ]
