# Generated by Django 2.1.5 on 2019-04-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0045_auto_20190413_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='hashed_id',
            field=models.CharField(default='3a8491a926fc4be484c0499921eefd45', max_length=255, unique=True),
        ),
    ]
