# Generated by Django 2.1.5 on 2019-04-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0053_auto_20190413_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='hashed_id',
            field=models.CharField(default='98dbc776a04b4a0da5222fbd105054c2', max_length=255, unique=True),
        ),
    ]
