# Generated by Django 2.1.5 on 2019-04-13 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0060_auto_20190414_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='votearchived',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes_archived', to='registration.Election', verbose_name='Election'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='hashed_id',
            field=models.CharField(default='8d8d2980922b42efb650162db3f36d0a', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='votearchived',
            name='hashed_id',
            field=models.CharField(default='3b44bc5613e947ee9ebdbf807c9fa833', max_length=255, unique=True),
        ),
    ]
