# Generated by Django 2.1.5 on 2019-04-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0064_auto_20190416_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='hashed_id',
            field=models.CharField(default='4e68d3f349d64e9aafcf4dca25287260', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='votearchived',
            name='hashed_id',
            field=models.CharField(default='45899c285ec340cdaeb7e0acc1aa1a8f', max_length=255, unique=True),
        ),
    ]
