# Generated by Django 2.1.5 on 2019-04-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0066_auto_20190417_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='general_plan_of_actions',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='hashed_id',
            field=models.CharField(default='de32097e85464495b9538c26b205d680', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='votearchived',
            name='hashed_id',
            field=models.CharField(default='16e95aa3b7c8475e800ad52e67bb7dd5', max_length=255, unique=True),
        ),
    ]
