# Generated by Django 2.1.7 on 2019-06-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0072_auto_20190425_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='display_name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='hashed_id',
            field=models.CharField(default='19e10545bf35485e9a77473b6ad9686f', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='votearchived',
            name='hashed_id',
            field=models.CharField(default='de5dd1ed85e04ade8e612b84d8220295', max_length=255, unique=True),
        ),
    ]
