# Generated by Django 2.1.5 on 2019-02-16 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=15, verbose_name='School Year')),
                ('grade_level', models.CharField(max_length=20, verbose_name='Grade Level')),
                ('section', models.CharField(max_length=20, verbose_name='Section')),
                ('registered_male_bosy', models.PositiveSmallIntegerField(verbose_name='Registered Male BoSY')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='School Name')),
                ('region', models.CharField(max_length=20, verbose_name='Region')),
                ('division', models.CharField(max_length=50, verbose_name='Division')),
                ('principal_name', models.CharField(max_length=100, verbose_name='Principal Name')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.School'),
        ),
    ]
