# Generated by Django 2.1.5 on 2019-02-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='registered_female_bosy',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Registered Female BoSY'),
        ),
        migrations.AddField(
            model_name='class',
            name='registered_female_eosy',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Registered Female EoSY'),
        ),
        migrations.AddField(
            model_name='class',
            name='registered_male_eosy',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Registered Male EoSY'),
        ),
        migrations.AddField(
            model_name='class',
            name='registered_total_bosy',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Registered Total BoSY'),
        ),
        migrations.AlterField(
            model_name='class',
            name='registered_male_bosy',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Registered Male BoSY'),
        ),
    ]
