# Generated by Django 2.1.5 on 2019-02-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20190216_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='registered_total_bosy',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Registered Total EoSY'),
        ),
    ]
