# Generated by Django 2.1.5 on 2019-02-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20190216_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressBarangay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_barangay', models.CharField(max_length=50, verbose_name='Address Barangay')),
            ],
        ),
        migrations.CreateModel(
            name='AddressMunicipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_municipality', models.CharField(max_length=50, verbose_name='Address Municipality')),
            ],
        ),
        migrations.CreateModel(
            name='EthnicGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnic_group', models.CharField(max_length=50, verbose_name='Ethnic Group')),
            ],
        ),
        migrations.CreateModel(
            name='MotherTounge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_tounge', models.CharField(max_length=50, verbose_name='Mother Tounge')),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religion', models.CharField(max_length=100, verbose_name='Religion')),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=1, verbose_name='Sex')),
            ],
        ),
    ]
