# Generated by Django 2.1.5 on 2019-02-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_addressbarangay_addressmunicipality_ethnicgroup_mothertounge_religion_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressProvince',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_province', models.CharField(max_length=100, verbose_name='Address Province')),
            ],
        ),
        migrations.AlterField(
            model_name='addressmunicipality',
            name='address_municipality',
            field=models.CharField(max_length=100, verbose_name='Address Municipality'),
        ),
    ]
