# Generated by Django 2.1.5 on 2019-02-16 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20190216_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_flag', models.CharField(choices=[('Y', 'Active'), ('N', 'Inactive')], max_length=1, verbose_name='Active Flag Identifier')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Student', verbose_name='Student')),
            ],
        ),
    ]
