# Generated by Django 2.1.5 on 2019-03-10 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0008_auto_20190310_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('school_year', models.CharField(max_length=20, verbose_name='School Year')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('election_day_from', models.DateField(verbose_name='Election Start Date')),
                ('election_day_to', models.DateField(verbose_name='Election End Date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', related_query_name='elections created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('last_udated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by', related_query_name='elections last updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
