# Generated by Django 2.1.5 on 2019-03-10 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_election'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='election',
            options={'ordering': ('-school_year', '-election_day_from')},
        ),
        migrations.AlterUniqueTogether(
            name='election',
            unique_together={('school_year', 'election_day_from', 'election_day_to')},
        ),
    ]
