# Generated by Django 2.1.5 on 2019-02-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_electionofficer'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_id',
            field=models.CharField(default='', max_length=10, verbose_name='School ID'),
        ),
        migrations.AlterField(
            model_name='school',
            name='division',
            field=models.CharField(default='', max_length=50, verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='School Name'),
        ),
        migrations.AlterField(
            model_name='school',
            name='principal_name',
            field=models.CharField(default='', max_length=150, verbose_name='Principal Name'),
        ),
        migrations.AlterField(
            model_name='school',
            name='region',
            field=models.CharField(default='', max_length=20, verbose_name='Region'),
        ),
    ]
