# Generated by Django 2.1.5 on 2019-02-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20190217_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='adviser',
            field=models.CharField(max_length=150, null=True, verbose_name='Adviser'),
        ),
        migrations.AlterField(
            model_name='class',
            name='grade_level',
            field=models.CharField(max_length=20, null=True, verbose_name='Grade Level'),
        ),
        migrations.AlterField(
            model_name='class',
            name='school_year',
            field=models.CharField(max_length=15, null=True, verbose_name='School Year'),
        ),
        migrations.AlterField(
            model_name='class',
            name='section',
            field=models.CharField(max_length=20, null=True, verbose_name='Section'),
        ),
    ]
