# Generated by Django 2.1.5 on 2019-02-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20190217_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='registered_total_eosy',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Registered Total EoSY'),
        ),
        migrations.AlterField(
            model_name='class',
            name='registered_total_bosy',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Registered Total BoSY'),
        ),
    ]
