# Generated by Django 2.1.5 on 2019-02-17 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20190217_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotherTongue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_tongue', models.CharField(max_length=50, verbose_name='Mother Tongue')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='mother_tounge',
        ),
        migrations.DeleteModel(
            name='MotherTounge',
        ),
        migrations.AddField(
            model_name='student',
            name='mother_tongue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.MotherTongue', verbose_name='Mother Tounge'),
        ),
    ]
