# Generated by Django 2.1.5 on 2019-03-13 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0013_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_created_by', related_query_name='position_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='position',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_updated_by', related_query_name='position_last_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated by'),
        ),
        migrations.AlterField(
            model_name='election',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_created_by', related_query_name='elections created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='election',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_updated_by', related_query_name='elections last updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated by'),
        ),
    ]
