# Generated by Django 2.1.5 on 2019-03-13 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20190313_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionGradeLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(max_length=20, verbose_name='Grade Level')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_grade_level', related_query_name='grade_levels', to='registration.Position', verbose_name='Position')),
            ],
        ),
    ]
