# Generated by Django 2.1.5 on 2019-03-17 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_auto_20190317_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates_created', related_query_name='position_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='registration.Election', verbose_name='Election'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates_last_updated', related_query_name='position_last_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated by'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='registration.Party', verbose_name='Party'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='registration.Position', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='registration.Student', verbose_name='Student'),
        ),
    ]
