# Generated by Django 2.1.5 on 2019-03-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0022_auto_20190318_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Title'),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('student', 'election')},
        ),
    ]
