# Generated by Django 2.1.5 on 2019-03-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_auto_20190321_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='school_year',
            field=models.CharField(db_index=True, max_length=15, null=True, verbose_name='School Year'),
        ),
    ]
