# Generated by Django 2.1.5 on 2019-03-27 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_candidate_profile_pic'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together=set(),
        ),
    ]
