# Generated by Django 2.1.5 on 2019-03-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0027_auto_20190327_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='election',
            options={'ordering': ('-election_day_from',)},
        ),
        migrations.AddField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('FINALIZED', 'FINALIZED'), ('COMPLETED', 'COMPLETED'), ('CANCELED', 'CANCELED')], default='NEW', max_length=20),
        ),
    ]
