# Generated by Django 2.1.5 on 2019-03-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0028_auto_20190328_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='is_token_generated',
            field=models.BooleanField(default=False, verbose_name='Token Available?'),
        ),
    ]
