# Generated by Django 2.1.5 on 2019-04-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0031_auto_20190331_0217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ('position', 'student')},
        ),
        migrations.AddField(
            model_name='voter',
            name='is_voted_cased',
            field=models.BooleanField(default=False, verbose_name='Vote casted?'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_token',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Token'),
        ),
    ]
