# Generated by Django 2.1.5 on 2019-04-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0032_auto_20190408_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='is_temporary_token',
            field=models.BooleanField(default=False, verbose_name='Temporary Token'),
        ),
        migrations.AddField(
            model_name='voter',
            name='voter_token_for_validation_h',
            field=models.CharField(max_length=250, null=True, verbose_name='Vote Validation Token'),
        ),
    ]
