# Generated by Django 2.1.5 on 2019-04-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0034_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='hashed_id',
            field=models.CharField(default='a411c6ffa4cd4c17a733ededcf08796b', max_length=255),
        ),
    ]
