# Generated by Django 2.1.5 on 2019-04-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0038_auto_20190409_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='hashed_id',
            field=models.CharField(default='d532071cbe804f03941ab4c653a1f00d', max_length=255, unique=True),
        ),
    ]
