# Generated by Django 2.1.5 on 2019-04-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0043_auto_20190413_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='hashed_id',
            field=models.CharField(default='babc16d4ba7d48c3ac9934c136ec1373', max_length=255, unique=True),
        ),
    ]
