# Generated by Django 2.1.5 on 2019-04-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0044_auto_20190413_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='hashed_id',
            field=models.CharField(default='40fb31bc2e4d416a8d639e05edfb9dc3', max_length=255, unique=True),
        ),
    ]
