# Generated by Django 2.1.5 on 2019-04-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0047_auto_20190413_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='hashed_id',
            field=models.CharField(default='19f4e90ae39a4aa8a0a2622dd610f19e', max_length=255, unique=True),
        ),
    ]
