# Generated by Django 2.1.5 on 2019-04-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0048_auto_20190413_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='hashed_id',
            field=models.CharField(default='a0479e5b25d54195a702b49e4ea92c9d', max_length=255, unique=True),
        ),
    ]
