# Generated by Django 2.1.5 on 2019-04-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0049_auto_20190413_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='hashed_id',
            field=models.CharField(default='3078ddce28e44eeca5891ac073b16f0d', max_length=255, unique=True),
        ),
    ]
