# Generated by Django 2.1.5 on 2019-04-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0052_auto_20190413_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='hashed_id',
            field=models.CharField(default='44de1efc230d43fdb7fb1ac17f6f0a35', max_length=255, unique=True),
        ),
    ]
