# Generated by Django 2.1.5 on 2019-04-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0054_auto_20190413_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='hashed_id',
            field=models.CharField(default='6563dccd5bdf4abab3405a7439ae8a62', max_length=255, unique=True),
        ),
    ]
