# Generated by Django 2.1.5 on 2019-04-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0056_auto_20190413_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='hashed_id',
            field=models.CharField(default='d63d62237cbe4eea8f5b6bac5aab021a', max_length=255, unique=True),
        ),
    ]
