# Generated by Django 2.1.5 on 2019-04-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0058_auto_20190414_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='hashed_id',
            field=models.CharField(default='11c494cec6314b53b6ee38d8ba04983c', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='votearchived',
            name='hashed_id',
            field=models.CharField(default='ced756d257c24c589afce500def025c8', max_length=255, unique=True),
        ),
    ]
