# Generated by Django 2.1.5 on 2019-04-13 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0061_auto_20190414_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='winnercandidate',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner_candidates', to='registration.Candidate', verbose_name='Candidate'),
        ),
        migrations.AddField(
            model_name='winnercandidate',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner_candidates', to='registration.Election', verbose_name='Election'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='hashed_id',
            field=models.CharField(default='8800df7f1e4044f885328bef7ec1fed4', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='votearchived',
            name='hashed_id',
            field=models.CharField(default='3467994788b5438c901b2f5d19329706', max_length=255, unique=True),
        ),
    ]
