# Generated by Django 2.1.5 on 2019-04-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0062_auto_20190414_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='winnercandidate',
            name='tie',
            field=models.BooleanField(default=False, verbose_name='Is Tie?'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='hashed_id',
            field=models.CharField(default='5744bcaf17494fe998135dcfc84ba973', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='votearchived',
            name='hashed_id',
            field=models.CharField(default='383fdd093fa94d7fab74c7e1ce1572b5', max_length=255, unique=True),
        ),
    ]
