# Generated by Django 2.1.5 on 2019-04-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0063_auto_20190414_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='hashed_id',
            field=models.CharField(default='dea3a5421fc046ed8738e633384f7082', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='votearchived',
            name='hashed_id',
            field=models.CharField(default='6788cb4dca184175988f086d0be8002a', max_length=255, unique=True),
        ),
    ]
