# Generated by Django 2.1.5 on 2019-04-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0065_auto_20190416_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winnercandidate',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='winnercandidate',
            name='election',
        ),
        migrations.AlterField(
            model_name='vote',
            name='hashed_id',
            field=models.CharField(default='2ed4247cac2d49198d529981efe8e2f7', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='votearchived',
            name='hashed_id',
            field=models.CharField(default='dd4d6e4a5fbe41adaff0c6afa42a837d', max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='WinnerCandidate',
        ),
    ]
