# Generated by Django 2.1.5 on 2019-04-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0068_auto_20190425_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='grade_level_integer',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='hashed_id',
            field=models.CharField(default='b19e51271f60458d97048a21922c85c0', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='votearchived',
            name='hashed_id',
            field=models.CharField(default='8a4f9f56327043b89334cc347ff362e2', max_length=255, unique=True),
        ),
    ]
