# Generated by Django 2.1.5 on 2019-04-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0070_auto_20190425_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='hashed_id',
            field=models.CharField(default='f0977d071ac042109c6ad13bbbc2810a', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='votearchived',
            name='hashed_id',
            field=models.CharField(default='73e2f1ad7e744db1a13e4d7006665a99', max_length=255, unique=True),
        ),
    ]
