# Generated by Django 2.1.5 on 2019-04-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0071_auto_20190425_0508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ('school_year', 'grade_level_integer', 'section')},
        ),
        migrations.AlterModelOptions(
            name='positiongradelevel',
            options={'ordering': ('grade_level_integer',)},
        ),
        migrations.AddField(
            model_name='positiongradelevel',
            name='grade_level_integer',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='hashed_id',
            field=models.CharField(default='e85e5365678f4c659a0c03b1d984fbfc', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='votearchived',
            name='hashed_id',
            field=models.CharField(default='00b39c9702f247d49e63a99432db0fb2', max_length=255, unique=True),
        ),
    ]
