# Generated by Django 2.1.7 on 2019-06-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0073_auto_20190603_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='hashed_id',
            field=models.CharField(default='f515db52a1d242b89f16995d48274f5e', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='votearchived',
            name='hashed_id',
            field=models.CharField(default='4f04f046ba6e4ac1af8d2a01510b3052', max_length=255, unique=True),
        ),
    ]
