# Generated by Django 2.1.5 on 2019-04-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_auto_20190413_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denomarmalizedvotes',
            name='voter_id_h',
            field=models.CharField(default='bfa89ddac8164128a78c15dab8cc6dac', max_length=255, unique=True, verbose_name='Hashed Voter ID'),
        ),
    ]
