# Generated by Django 2.1.5 on 2019-04-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_auto_20190413_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denomarmalizedvotes',
            name='voter_id_h',
            field=models.CharField(default='cf271e348e1a482c930b3a86d6aa6a07', max_length=255, unique=True, verbose_name='Hashed Voter ID'),
        ),
    ]
