# Generated by Django 2.1.5 on 2019-04-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0012_auto_20190413_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denomarmalizedvotes',
            name='voter_id_h',
            field=models.CharField(default='59de3efc0e5d4caf8bf0956c1fa8df29', max_length=255, verbose_name='Hashed Voter ID'),
        ),
    ]
