# Generated by Django 2.1.5 on 2019-04-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0018_auto_20190414_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denomarmalizedvotes',
            name='voter_id_h',
            field=models.CharField(default='881ba96024824f54b316d82d980d2073', max_length=255, verbose_name='Hashed Voter ID'),
        ),
    ]
