# Generated by Django 2.1.5 on 2019-04-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0020_auto_20190414_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='denomarmalizedvotes',
            name='candidate_position_priority',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='denomarmalizedvotes',
            name='voter_id_h',
            field=models.CharField(default='4cc1709bc42445f6913996900a4cf15a', max_length=255, verbose_name='Hashed Voter ID'),
        ),
    ]
