# Generated by Django 2.1.5 on 2019-04-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0023_auto_20190417_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='winnercandidatedenormalized',
            name='tie',
            field=models.BooleanField(default=False, verbose_name='Is Tie?'),
        ),
        migrations.AlterField(
            model_name='denormalizedvotes',
            name='voter_id_h',
            field=models.CharField(default='23e55ca5fead4986899c89b0e321d3b6', max_length=255, verbose_name='Hashed Voter ID'),
        ),
    ]
